# Generated by Django 3.1.1 on 2020-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201003_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isowner',
            field=models.BooleanField(default=False, verbose_name='isowner'),
        ),
    ]
