# Generated by Django 3.1.1 on 2020-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_favitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favitems',
            name='Items',
        ),
        migrations.AddField(
            model_name='favitems',
            name='shops',
            field=models.ManyToManyField(related_name='user_fav', to='app_api.Shop'),
        ),
    ]
