# Generated by Django 3.1.1 on 2020-10-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_remove_shop_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOwner',
        ),
    ]
