# Generated by Django 3.1.1 on 2020-10-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0013_shop_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner',
            new_name='user',
        ),
    ]
