# Generated by Django 3.1.1 on 2020-10-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0014_auto_20201003_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
    ]
