# Generated by Django 3.1.1 on 2020-10-03 16:41

import app_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0015_auto_20201003_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image_url',
            field=models.ImageField(null=True, upload_to=app_api.models.recipe_image_file_path),
        ),
    ]
