# Generated by Django 3.1.1 on 2020-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0016_auto_20201003_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
